export const TODOLIST_CHANGE = 'TODOLIST_CHANGE';
export const ADD_TODO = 'ADD_TODO';
export const GET_TODOS = 'GET_TODOS';
export const TODO_CHANGE_STATUS = 'TODO_CHANGE_STATUS';
export const TODOS_CHANGE = 'TODOS_CHANGE';
export const COMPLETED_TODO_VISIBILITY_CHANGE =
  'COMPLETED_TODO_VISIBILITY_CHANGE';
export const USER_SIGNING = 'USER_SIGNING';
export const USER_SIGNING_SUCCESS = 'USER_SIGNING_SUCCESS';
export const USER_SIGNING_FAILED = 'USER_SIGNING_FAILED';
export const USER_SIGNING_ABORT = 'USER_SIGNING_ABORT';
export const USER_DISCONNECT = 'USER_DISCONNECT';
